// ══════════════════════════════════════════════════
// data.js — サンプルデータ（GAS未接続時のフォールバック）
// ══════════════════════════════════════════════════

const SAMPLE_PRODUCTS = [
  // ── マグロ ───────────────────────────────────────
  {
    id: "TUNA-001", category: "マグロ",
    name_ja: "愛媛県産養殖生本まぐろ 背上 UB",
    name_en: "Farmed Bluefin Tuna - Upper Back (UB)",
    origin: "愛媛 / Ehime", size: "70kgサイズ / 3-4kg個体",
    desc_ja: "愛媛県産養殖生本まぐろの背上部位。サイズ約3-4kg。",
    desc_en: "Upper back of farmed bluefin tuna from Ehime. Approx 3-4kg.",
    price: 62.93, unit: "kg", min: 0.5, step: 0.5, featured: false,
    note_ja: "3kg以下カット+$5", note_en: "Cut +$5 for under 3kg",
    icon: "🐟", image_url: "images/tuna/ub.jpg",
  },
  {
    id: "TUNA-002", category: "マグロ",
    name_ja: "愛媛県産養殖生本まぐろ 背中 MB",
    name_en: "Farmed Bluefin Tuna - Middle Back (MB)",
    origin: "愛媛 / Ehime", size: "70kgサイズ / 3-4kg個体",
    desc_ja: "背中部位。バランスの良い赤身と脂。",
    desc_en: "Middle back. Well-balanced lean and fat.",
    price: 86.36, unit: "kg", min: 0.5, step: 0.5, featured: false,
    note_ja: "3kg以下カット+$5", note_en: "Cut +$5 for under 3kg",
    icon: "🐟", image_url: "images/tuna/mb.jpg",
  },
  {
    id: "TUNA-003", category: "マグロ",
    name_ja: "愛媛県産養殖生本まぐろ 背下 BB",
    name_en: "Farmed Bluefin Tuna - Bottom Back (BB)",
    origin: "愛媛 / Ehime", size: "70kgサイズ / 3-4kg個体",
    desc_ja: "背下部位。旨みが凝縮した赤身寄りの部位。",
    desc_en: "Bottom back. Lean with concentrated umami.",
    price: 62.06, unit: "kg", min: 0.5, step: 0.5, featured: false,
    note_ja: "3kg以下カット+$5", note_en: "Cut +$5 for under 3kg",
    icon: "🐟", image_url: "images/tuna/bb.jpg",
  },
  {
    id: "TUNA-004", category: "マグロ",
    name_ja: "愛媛県産養殖生本まぐろ 腹上 UA（大トロ）",
    name_en: "Farmed Bluefin Tuna - Upper Abdomen UA (Otoro)",
    origin: "愛媛 / Ehime", size: "70kgサイズ / 3-4kg個体",
    desc_ja: "最高峰の大トロ部位。とろける脂が絶品。",
    desc_en: "Premium otoro. Melts in your mouth.",
    price: 102.86, unit: "kg", min: 0.5, step: 0.5, featured: true,
    note_ja: "3kg以下カット+$5", note_en: "Cut +$5 for under 3kg",
    icon: "🐟", image_url: "images/tuna/ua.jpg",
  },
  {
    id: "TUNA-005", category: "マグロ",
    name_ja: "愛媛県産養殖生本まぐろ 腹中 MA（中トロ）",
    name_en: "Farmed Bluefin Tuna - Middle Abdomen MA (Chutoro)",
    origin: "愛媛 / Ehime", size: "70kgサイズ / 3-4kg個体",
    desc_ja: "人気No.1の中トロ部位。赤身と脂の黄金バランス。",
    desc_en: "Most popular chutoro. Perfect balance of lean and fat.",
    price: 86.36, unit: "kg", min: 0.5, step: 0.5, featured: false,
    note_ja: "3kg以下カット+$5", note_en: "Cut +$5 for under 3kg",
    icon: "🐟", image_url: "images/tuna/ma.jpg",
  },
  {
    id: "TUNA-006", category: "マグロ",
    name_ja: "愛媛県産養殖生本まぐろ 腹下 BA",
    name_en: "Farmed Bluefin Tuna - Bottom Abdomen BA",
    origin: "愛媛 / Ehime", size: "70kgサイズ / 3-4kg個体",
    desc_ja: "腹下部位。脂と旨みのバランスが良い人気部位。",
    desc_en: "Bottom abdomen. Popular cut with great flavor balance.",
    price: 62.93, unit: "kg", min: 0.5, step: 0.5, featured: false,
    note_ja: "3kg以下カット+$5", note_en: "Cut +$5 for under 3kg",
    icon: "🐟", image_url: "images/tuna/ba.jpg",
  },

  // ── 雲丹 ─────────────────────────────────────────
  {
    id: "UNI-S01", category: "雲丹",
    name_ja: "雲丹 泰匠物産・艶然（ロシア産赤上並び）",
    name_en: "Uni - Taisho Enzen / Russian Red Grade",
    origin: "ロシア / Russia", size: "250g / pack",
    desc_ja: "ロシア産赤上並びの最高グレード。泰匠物産・艶然ブランド。",
    desc_en: "Top grade Russian Red uni. Taisho Enzen brand.",
    price: 159.46, unit: "pack", min: 1, step: 1, featured: true,
    note_ja: "仕入状況により変動あり", note_en: "Subject to supply conditions",
    icon: "🦔", image_url: "images/uni/s01.jpg",
  },
  {
    id: "UNI-S02", category: "雲丹",
    name_ja: "雲丹 倖永（ロシア）",
    name_en: "Uni - Kouei / Russia",
    origin: "ロシア / Russia", size: "250g / pack",
    desc_ja: "倖永ブランドのロシア産雲丹。濃厚な甘みと磯の香り。",
    desc_en: "Kouei brand Russian uni. Rich sweetness with ocean aroma.",
    price: 168.14, unit: "pack", min: 1, step: 1, featured: false,
    note_ja: "仕入状況により変動あり", note_en: "Subject to supply conditions",
    icon: "🦔", image_url: "images/uni/s02.jpg",
  },
  {
    id: "UNI-S03", category: "雲丹",
    name_ja: "雲丹 竹内（ロシア産赤上並び）",
    name_en: "Uni - Takeuchi / Russian Red",
    origin: "ロシア / Russia", size: "250g / pack",
    desc_ja: "竹内ブランドのロシア産赤上並び雲丹。",
    desc_en: "Takeuchi brand Russian Red grade uni.",
    price: 133.42, unit: "pack", min: 1, step: 1, featured: false,
    note_ja: "仕入状況により変動あり", note_en: "Subject to supply conditions",
    icon: "🦔", image_url: "images/uni/s03.jpg",
  },
  {
    id: "UNI-S04", category: "雲丹",
    name_ja: "雲丹 松浦（ロシア産黄色）",
    name_en: "Uni - Matsuura / Russian Yellow",
    origin: "ロシア / Russia", size: "250g / pack",
    desc_ja: "松浦ブランドのロシア産黄色雲丹。まろやかな風味。",
    desc_en: "Matsuura brand Russian Yellow uni. Mellow flavor.",
    price: 133.42, unit: "pack", min: 1, step: 1, featured: false,
    note_ja: "仕入状況により変動あり", note_en: "Subject to supply conditions",
    icon: "🦔", image_url: "images/uni/s04.jpg",
  },
  {
    id: "UNI-S07", category: "雲丹",
    name_ja: "雲丹 マルカワ（ロシア産赤上並び）",
    name_en: "Uni - Marukawa / Russian Red",
    origin: "ロシア / Russia", size: "250g / pack",
    desc_ja: "マルカワブランドのロシア産赤上並び雲丹。",
    desc_en: "Marukawa brand Russian Red grade uni.",
    price: 150.78, unit: "pack", min: 1, step: 1, featured: false,
    note_ja: "仕入状況により変動あり", note_en: "Subject to supply conditions",
    icon: "🦔", image_url: "images/uni/s07.jpg",
  },
  {
    id: "UNI-S11", category: "雲丹",
    name_ja: "雲丹 浜中小川（Bバラ）",
    name_en: "Uni - Hamanaka Ogawa / B Grade Bara",
    origin: "ロシア / Russia", size: "250g / pack",
    desc_ja: "リーズナブルなBバラグレード。料理用にも最適。",
    desc_en: "Value B grade bara uni. Great for cooking.",
    price: 98.70, unit: "pack", min: 1, step: 1, featured: false,
    note_ja: "仕入状況により変動あり", note_en: "Subject to supply conditions",
    icon: "🦔", image_url: "images/uni/s11.jpg",
  },
  {
    id: "UNI-S15", category: "雲丹",
    name_ja: "雲丹 壱（カナダBARA）",
    name_en: "Uni - Ichi / Canada Bara",
    origin: "カナダ / Canada", size: "250g / pack",
    desc_ja: "カナダ産のバラグレード雲丹。",
    desc_en: "Canadian bara grade uni.",
    price: 98.70, unit: "pack", min: 1, step: 1, featured: false,
    note_ja: "仕入状況により変動あり", note_en: "Subject to supply conditions",
    icon: "🦔", image_url: "images/uni/s15.jpg",
  },

  // ── 養殖 ─────────────────────────────────────────
  {
    id: "FARM-K01", category: "養殖",
    name_ja: "朝〆養殖たい（愛媛）",
    name_en: "Farmed Sea Bream Morning Kill (Ehime)",
    origin: "愛媛 / Ehime", size: "1.5kg前後",
    desc_ja: "愛媛県産の養殖真鯛。朝〆で新鮮さ抜群。",
    desc_en: "Farmed sea bream from Ehime. Morning-killed for peak freshness.",
    price: 31.70, unit: "kg", min: 0.5, step: 0.5, featured: false,
    note_ja: "朝〆", note_en: "Morning Kill",
    icon: "🐡", image_url: "images/farmed/k01.jpg",
  },
  {
    id: "FARM-K02", category: "養殖",
    name_ja: "朝〆養殖カンパチ（鹿児島）",
    name_en: "Farmed Amberjack Morning Kill (Kagoshima)",
    origin: "鹿児島 / Kagoshima", size: "2-3kg前後",
    desc_ja: "鹿児島産の養殖カンパチ。朝〆で旨みが凝縮。",
    desc_en: "Farmed amberjack from Kagoshima. Morning-killed.",
    price: 42.12, unit: "kg", min: 0.5, step: 0.5, featured: true,
    note_ja: "朝〆", note_en: "Morning Kill",
    icon: "🐠", image_url: "images/farmed/k02.jpg",
  },
  {
    id: "FARM-K03", category: "養殖",
    name_ja: "養殖ブリ新物（鹿児島）",
    name_en: "Farmed Yellowtail New Season (Kagoshima)",
    origin: "鹿児島 / Kagoshima", size: "3-4kg前後",
    desc_ja: "鹿児島産の養殖ブリ新物。脂乗り抜群。",
    desc_en: "New season farmed yellowtail from Kagoshima. Excellent fat content.",
    price: 37.34, unit: "kg", min: 0.5, step: 0.5, featured: false,
    note_ja: "新物", note_en: "New Season",
    icon: "🐟", image_url: "images/farmed/k03.jpg",
  },
  {
    id: "FARM-K04", category: "養殖",
    name_ja: "朝〆養殖シマアジ（愛媛）",
    name_en: "Farmed Striped Jack Morning Kill (Ehime)",
    origin: "愛媛 / Ehime", size: "0.9kg前後",
    desc_ja: "愛媛県産養殖シマアジ。朝〆の新鮮なシマアジは絶品。",
    desc_en: "Farmed striped jack from Ehime. Morning-killed.",
    price: 48.19, unit: "kg", min: 0.5, step: 0.5, featured: false,
    note_ja: "朝〆", note_en: "Morning Kill",
    icon: "🐟", image_url: "images/farmed/k04.jpg",
  },
  {
    id: "FARM-K05", category: "養殖",
    name_ja: "朝〆養殖平目（韓国）",
    name_en: "Farmed Flounder Morning Kill (Korea)",
    origin: "韓国 / Korea", size: "1kg前後",
    desc_ja: "韓国産養殖ヒラメ。朝〆で歯ごたえ抜群。",
    desc_en: "Farmed flounder from Korea. Morning-killed.",
    price: 51.64, unit: "kg", min: 0.5, step: 0.5, featured: false,
    note_ja: "朝〆", note_en: "Morning Kill",
    icon: "🐡", image_url: "images/farmed/k05.jpg",
  },

  // ── 魚介類 ───────────────────────────────────────
  {
    id: "SEA-K75", category: "魚介類",
    name_ja: "あん肝（北海道噴火湾・中）",
    name_en: "Monkfish Liver (Hokkaido Funka Bay, Medium)",
    origin: "北海道 / Hokkaido", size: "1kg",
    desc_ja: "北海道噴火湾産のあん肝。海のフォアグラ。",
    desc_en: "Monkfish liver from Hokkaido Funka Bay. Foie gras of the sea.",
    price: 153.20, unit: "kg", min: 0.5, step: 0.5, featured: false,
    note_ja: "", note_en: "",
    icon: "🫁", image_url: "images/seafood/k75.jpg",
  },
  {
    id: "SEA-K76", category: "魚介類",
    name_ja: "あん肝（青森・中大）",
    name_en: "Monkfish Liver (Aomori, Med-Large)",
    origin: "青森 / Aomori", size: "1kg",
    desc_ja: "青森産の中大サイズあん肝。濃厚な旨み。",
    desc_en: "Medium-large monkfish liver from Aomori.",
    price: 83.76, unit: "kg", min: 0.5, step: 0.5, featured: false,
    note_ja: "", note_en: "",
    icon: "🫁", image_url: "images/seafood/k76.jpg",
  },
  {
    id: "SEA-K83", category: "魚介類",
    name_ja: "アカガイ（宮城）",
    name_en: "Ark Shell (Miyagi)",
    origin: "宮城 / Miyagi", size: "100/140g前後",
    desc_ja: "宮城産の天然アカガイ。磯の香りと濃厚な旨み。",
    desc_en: "Wild ark shell from Miyagi. Rich ocean flavor.",
    price: 62.06, unit: "kg", min: 1, step: 1, featured: false,
    note_ja: "", note_en: "",
    icon: "🦪", image_url: "images/seafood/k83.jpg",
  },
  {
    id: "SEA-K88", category: "魚介類",
    name_ja: "サザエ（長崎）S",
    name_en: "Turban Shell (Nagasaki, S)",
    origin: "長崎 / Nagasaki", size: "100/130g前後",
    desc_ja: "長崎産のサザエ。壺焼きに最適。",
    desc_en: "Turban shell from Nagasaki. Perfect for grilling.",
    price: 40.36, unit: "kg", min: 1, step: 1, featured: false,
    note_ja: "", note_en: "",
    icon: "🐚", image_url: "images/seafood/k88.jpg",
  },
  {
    id: "SEA-P70", category: "魚介類",
    name_ja: "マダラ白子フレッシュパック（2特）",
    name_en: "Pacific Cod Milt Fresh Pack Grade 2",
    origin: "国内 / Japan", size: "0.5kg / pack",
    desc_ja: "新鮮なマダラの白子。とろける食感。",
    desc_en: "Fresh Pacific cod milt. Silky texture.",
    price: 43.03, unit: "pack", min: 1, step: 1, featured: false,
    note_ja: "", note_en: "",
    icon: "🫀", image_url: "images/seafood/p70.jpg",
  },

  // ── 牡蠣 ─────────────────────────────────────────
  {
    id: "OYS-P115", category: "牡蠣",
    name_ja: "カキ ヒロタ湾 M",
    name_en: "Oyster Hirota Bay M",
    origin: "広田湾", size: "131-200g前後",
    desc_ja: "広田湾産の牡蠣。濃厚な旨みが自慢。",
    desc_en: "Oyster from Hirota Bay. Rich and flavorful.",
    price: 6.60, unit: "pc", min: 1, step: 1, featured: false,
    note_ja: "", note_en: "",
    icon: "🦪", image_url: "images/oyster/p115.jpg",
  },
  {
    id: "OYS-P122", category: "牡蠣",
    name_ja: "兵庫県室津産 殻付冷凍牡蠣 2L（生食可）",
    name_en: "Frozen Oyster in Shell 2L Hyogo Murotsu (Sashimi Grade)",
    origin: "兵庫 室津 / Hyogo Murotsu", size: "2kg前後 / 20個",
    desc_ja: "生食可の高品質冷凍牡蠣。兵庫県室津産。",
    desc_en: "Sashimi grade frozen oyster in shell. Hyogo Murotsu.",
    price: 69.87, unit: "pack", min: 1, step: 1, featured: false,
    note_ja: "生食可", note_en: "Sashimi Grade",
    icon: "🦪", image_url: "images/oyster/p122.jpg",
  },
  {
    id: "OYS-P126", category: "牡蠣",
    name_ja: "カキ 広田湾 L",
    name_en: "Oyster Hirota Bay L",
    origin: "広田湾", size: "200/280g前後",
    desc_ja: "広田湾産の大粒牡蠣L。",
    desc_en: "Large oyster from Hirota Bay.",
    price: 9.30, unit: "pc", min: 1, step: 1, featured: false,
    note_ja: "", note_en: "",
    icon: "🦪", image_url: "images/oyster/p126.jpg",
  },

  // ── 冷凍品 ───────────────────────────────────────
  {
    id: "FRZ-P51", category: "冷凍品",
    name_ja: "冷凍鮭いくら（輸入）",
    name_en: "Frozen Salmon Roe / Ikura (Imported)",
    origin: "輸入 / Imported", size: "0.5kg前後 / pack",
    desc_ja: "輸入物の冷凍鮭いくら。コスパ抜群。",
    desc_en: "Imported frozen salmon roe. Excellent value.",
    price: 73.18, unit: "pack", min: 1, step: 1, featured: false,
    note_ja: "", note_en: "",
    icon: "🫧", image_url: "images/frozen/p51.jpg",
  },
  {
    id: "FRZ-P52", category: "冷凍品",
    name_ja: "冷凍新物鮭いくら（北海道 日高）",
    name_en: "Frozen Salmon Roe New Season (Hokkaido Hidaka)",
    origin: "北海道 日高 / Hokkaido Hidaka", size: "0.5kg前後 / pack",
    desc_ja: "北海道日高産の新物鮭いくら。大粒で濃厚。",
    desc_en: "New season salmon roe from Hokkaido Hidaka. Large grains.",
    price: 113.62, unit: "pack", min: 1, step: 1, featured: false,
    note_ja: "新物", note_en: "New Season",
    icon: "🫧", image_url: "images/frozen/p52.jpg",
  },
  {
    id: "FRZ-P55", category: "冷凍品",
    name_ja: "冷凍ボタンエビ 11-13入（ロシア）",
    name_en: "Frozen Botan Shrimp / Spot Prawn (Russia)",
    origin: "ロシア / Russia", size: "0.5kg / 11-13尾",
    desc_ja: "ロシア産の冷凍ボタンエビ。甘みと濃厚な旨み。",
    desc_en: "Frozen spot prawn from Russia. Sweet and rich.",
    price: 53.73, unit: "pack", min: 1, step: 1, featured: false,
    note_ja: "11-13尾入", note_en: "11-13 pcs",
    icon: "🦐", image_url: "images/frozen/p55.jpg",
  },
  {
    id: "FRZ-P57", category: "冷凍品",
    name_ja: "冷凍甘エビ 61-67入（ロシア）",
    name_en: "Frozen Sweet Shrimp / Amaebi (Russia)",
    origin: "ロシア / Russia", size: "1kg / 61-67尾",
    desc_ja: "ロシア産の冷凍甘エビ。たっぷり入り。",
    desc_en: "Frozen sweet shrimp from Russia. 61-67 pcs.",
    price: 55.32, unit: "pack", min: 1, step: 1, featured: false,
    note_ja: "61-67尾入", note_en: "61-67 pcs",
    icon: "🦐", image_url: "images/frozen/p57.jpg",
  },
  {
    id: "FRZ-P56", category: "冷凍品",
    name_ja: "冷凍煮穴子 5尾（250g）",
    name_en: "Frozen Boiled Conger Eel (5 pcs)",
    origin: "国内 / Japan", size: "0.25kg / 5尾",
    desc_ja: "ふっくら柔らかい煮穴子。5尾入り。",
    desc_en: "Tender boiled conger eel. 5 pieces.",
    price: 19.03, unit: "pack", min: 1, step: 1, featured: false,
    note_ja: "5尾入", note_en: "5 pcs",
    icon: "🐍", image_url: "images/frozen/p56.jpg",
  },
  {
    id: "FRZ-P99", category: "冷凍品",
    name_ja: "細もずく（沖縄）",
    name_en: "Mozuku Seaweed Thin Type (Okinawa)",
    origin: "沖縄 / Okinawa", size: "1kg / pack",
    desc_ja: "沖縄産の細もずく。磯の香りが豊か。",
    desc_en: "Thin mozuku seaweed from Okinawa.",
    price: 29.51, unit: "pack", min: 1, step: 1, featured: false,
    note_ja: "", note_en: "",
    icon: "🌿", image_url: "images/frozen/p99.jpg",
  },
];
